title: Zong He's Personal Website
description: "Zong He’s GitHub Page."
author:
  name: "Zong He"
  email: "z0nghe@foxmail.com"
  url: "https://z0nghe.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Z0nghe"
year : "2020"
